<?php

/**
 * Includes the various user types that are generated by this factory.
 *
 * The User is an abstract base class. The Admin is a class correspoding to
 * 'read-write' permissions, the Volunteer corresponds to 'help' permissions, 
 * and the Reader corresponds to the 'read' permission.
 *
 * @since	1.0.0
 */
include_once( 'users/user.php' );
include_once( 'users/admin.php' );
include_once( 'users/volunteer.php' );
include_once( 'users/reader.php' );

/**
 * The class definition for the Simple Factory Pattern.
 *
 * This class includes a single method - get_user - which is responsible for returning
 * the proper user based on the incoming permissions.
 *
 * @package    lib
 * @author     Tom McFarlin <tom@tommcfarlin.com>
 * @copyright  2013 Tom McFarlin
 * @license    http://opensource.org/licenses/MIT
 * @version    1.0.0
 * @link       http://github.com/tommcfarlin/simple-factory-example/
 */
class Simple_Factory {
    
    /**
     * Returns the type of user requested based on the specified type.
     *
     * Examines the incoming permission the instatiates a user type corresponding to said
     * permission.
     *
     * @param	string	$permission 	The type of permissions the user is able to request. Possible
     *									values include 'read-write', 'read', 'help'.
     * @return	User					A subclass of the abstract User base class. Possible values include 'Admin',
     *									'Volunteer', 'Reader', and 'null' if an invalid permission is passed.
     * @since 	1.0.0
     */
    public function get_user( $permission ) {
        
        switch ( strtolower( $permission ) ) {
            
            case 'read-write':
                $user = new Admin();
                break;
            
            case 'help':
                $user = new Volunteer();
                break;
            
            case 'read':
                $user = new Reader();
                break;
            
            default:
                $user = null;
                break;
                
        }
        
        return $user;
        
    }
    
}